### ISSUE TITLE
Support resolving multiple font files in the same file covering different unicode ranges

### ISSUE THREAD

**Issue by nicoburns** [linebender/parley#322]
Consider this `@font-face` configuration (taken from https://servo.org):

```css
/* latin */
@font-face {
  font-family: 'Space Grotesk';
  font-style: normal;
  font-weight: 400;
  font-stretch: 100%;
  src: url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-latin-400-normal.woff2) format('woff2'), url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-latin-400-normal.woff) format('woff'); 
  unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;
}

/* latin-ext */
@font-face {
  font-family: 'Space Grotesk';
  font-style: normal;
  font-weight: 400;
  font-stretch: 100%;
  src: url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-latin-ext-400-normal.woff2) format('woff2'), url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-latin-ext-400-normal.woff) format('woff'); 
  unicode-range: U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;
}

/* vietnamese */
@font-face {
  font-family: 'Space Grotesk';
  font-style: normal;
  font-weight: 400;
  font-stretch: 100%;
  src: url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-vietnamese-400-normal.woff2) format('woff2'), url(https://fonts.bunny.net/space-grotesk/files/space-grotesk-vietnamese-400-normal.woff) format('woff'); 
  unicode-range: U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;
}
```

Source:  https://fonts.bunny.net/css?family=space-grotesk:400

Here we have 3 fonts with the same family name and attributes differing only in unicode range coverage. My reading of our current font fallback code is that only one of these will ever be tried because it is assumed that there will only be one font in each family with each uniqe set of attributes.

We should ensure that our font querying supports this case.
